version: "3.9"

services:
  db:
    image: postgres:16
    container_name: cckmobilya_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: furniture
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d furniture"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:

